### ISSUE TITLE
Interface gráfica para consultas

### ISSUE THREAD

**Issue by filipefbn** [MPMG-DCC-UFMG/M07#14]
Implementar interface gráfica a ser utilizada com a instância do Elasticsearch na host do LATIN.
Definir com Luís viabilidade de aproveitar o Áduna ou construir uma interface REST via Django.

**Comment by luiznery** [comment]
https://github.com/dzharii/awesome-elasticsearch
https://www.elastic.co/guide/en/logstash/7.6/index.html
