### ISSUE TITLE
Configurar integração contínua via Jenkins

### ISSUE THREAD

**Issue by filipefbn** [MPMG-DCC-UFMG/M07#21]

**Comment by rafaelglater** [comment]
Instalando o Jenkins
https://www.digitalocean.com/community/tutorials/how-to-install-jenkins-on-ubuntu-18-04

Colocando o Jenkins pra rodar juntos com os outros sites no nginx:
https://www.digitalocean.com/community/tutorials/how-to-configure-jenkins-with-ssl-using-an-nginx-reverse-proxy-on-ubuntu-18-04

**Comment by rafaelglater** [comment]
Acabei criando um subdomínio jenkins.host27...

E um novo certificado pra esse subdomínio:

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/jenkins.host27.adm.se.latin.dcc.ufmg.br/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/jenkins.host27.adm.se.latin.dcc.ufmg.br/privkey.pem
   Your cert will expire on 2020-08-10. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
