### ISSUE TITLE
Caracterizar amostra de dados do Elasticsearch e PostgreSQL

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/M07#7]

**Comment by filipefbn** [comment]
Enquanto não temos acesso aos dados, a caracterização para o entregável M07.1 está sendo feita em cima das amostras disponibilizadas no canal #m05 do Discord.

**Filipe Nascimento**: 
PostgreSQL 
- Amostras de tabelas dos schemas lins_olap e aduna_oltp disponíveis nos arquivos schema_aduna_oltp_amostra_das_tabelas.tar.gz e schema_lins_olap_amostra_das_tabelas.tar.gz

**Luiz Nery**: 
Elasticsearch
- Resultados de buscas disponíveis no arquivo schema_carga_gsi_stg_full.tar.gz
