### ISSUE TITLE
Caracterizar todos os dados do Elasticsearch, PostgreSQL e log (via SSH ou presencialmente)

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/M07#8]

**Comment by filipefbn** [comment]
1. Mensurar o tamanho dos dados
2. Caracterizar os dados com relação à frequência de palavras, qtd. de campos de palavras e caracteres (separados por cada tipo e geral)

**Comment by filipefbn** [comment]
Dependendo da resolução de #11

**Comment by filipefbn** [comment]
Foram caracterizados os dados do Elastic, conforme visto no entregável M07.1. Não obtivemos acesso aos outros.
